-- ============================================================================
-- FlowOps — Add draft_number to form_drafts + independent draft number sequence
-- ============================================================================
-- This migration adds:
--   1. A `draftNumber` column to form_drafts (TEXT, nullable — only order
--      drafts get a number, product drafts don't need one)
--   2. A PostgreSQL SEQUENCE `draft_order_number_seq` that is completely
--      independent from the real order number generation mechanism
--      (generate_order_number SQL function which uses MAX+1 on the Order
--      table). This sequence is global (not per-company) — draft numbers
--      are DRAFT-001, DRAFT-002, etc. across the entire system.
--
-- CRITICAL: This sequence shares NO logic, NO counter state, and NO code path
-- with the real order number sequence. The real order number is generated by
-- the generate_order_number() SQL function which does MAX(flowopsOrderNumber)+1
-- on the "Order" table — completely separate from this sequence.
-- ============================================================================

BEGIN;

-- Add draftNumber column to form_drafts
ALTER TABLE form_drafts
  ADD COLUMN IF NOT EXISTS "draftNumber" TEXT;

-- Create an independent sequence for draft order numbers
-- Starts at 1, increments by 1, never cycles
CREATE SEQUENCE IF NOT EXISTS draft_order_number_seq
  START WITH 1
  INCREMENT BY 1
  NO CYCLE;

-- Create a helper function to generate the next draft number
-- Format: DRAFT-{sequence_number} (zero-padded to 5 digits for consistency
-- with the real ORD-{year}-{5-digit} format)
CREATE OR REPLACE FUNCTION generate_draft_number()
RETURNS TEXT
LANGUAGE sql
AS $$
  SELECT 'DRAFT-' || LPAD(nextval('draft_order_number_seq')::TEXT, 5, '0');
$$;

COMMIT;
